<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FileManagerInstaller</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\file2manager\src\File2Manager.Core\File2Manager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="InstallerApp.xaml" />
    <Page Include="InstallerWindow.xaml" />
    <Compile Include="InstallerApp.xaml.cs" />
    <Compile Include="InstallerWindow.xaml.cs" />
  </ItemGroup>

</Project>
