#pragma once

/* ==========================================================================
 *  SRS Feature Map - Search Reflection
 * --------------------------------------------------------------------------
 *  Implements REQ-4.2.3.11 by translating Smart Search query text into the
 *  same internal tag vocabulary generated by rules.h and stored by storage.h.
 *  Search engines can use these tags as filters, boosts, or ranking features.
 * ========================================================================== */
#include <string>
#include <vector>

#include "collection_utils.h"
#include "rules.h"
#include "text_utils.h"
#include "types.h"

namespace categorization {
    /// REQ-4.2.3.11: infer media family from query terms.
    inline std::string mediaTypeFromQuery(const std::string& q) {
        static constexpr detail::Rule rules[] = {
            {"document", "document|file|pdf|paper|thesis|article|assignment|homework|report|slides|presentation|spreadsheet|notes"},
            {"image",    "image|photo|picture|screenshot|diagram|figure|icon|logo"},
            {"video",    "video|movie|recording|lecture video|clip"},
            {"audio",    "audio|music|song|voice|recording|podcast"},
            {"archive",  "archive|zip|compressed|backup"},
            {"code",     "code|source|program|script|notebook"},
            {"data",     "data|dataset|csv|json|log"},
        };
        return firstMatch(q, rules, "other");
    }
    /// REQ-4.2.3.11: infer explicit extension from query terms.
    inline std::string extensionFromQuery(const std::string& q) {
        static constexpr detail::Rule rules[] = {
            {".pdf",  "pdf"},         {".docx", "docx|word document"},
            {".pptx", "ppt|pptx|powerpoint|slides|presentation"},
            {".xlsx", "xls|xlsx|excel|spreadsheet"},
            {".txt",  "txt|text file|plain text"}, {".md",   "markdown|md"},
            {".jpg",  "jpg|jpeg|photo|picture"},   {".png",  "png|screenshot"},
            {".zip",  "zip|archive"},              {".cpp",  "cpp|c plus plus"},
            {".py",   "python|py"},                {".ipynb","jupyter|notebook|ipynb"},
        };
        return firstMatch(q, rules, "");
    }
    /// REQ-4.2.3.11: push "prefix:label" once.
    inline void addReflectedTag(SearchReflection& r, const std::string& prefix, const std::string& value) {
        const std::string c = label(value);
        if (!c.empty())
            pushUnique(r.tags, prefix + ":" + c);
    }
    /// REQ-4.2.3.11: whole-query and per-token keyword tags.
    inline void addKeywordReflection(SearchReflection& r, const std::string& query) {
        const std::string c = label(query);
        if (c.empty())
            return;
        pushUnique(r.keywordTags, "keyword:" + c);
        std::string word;
        for (char ch : c) {
            if (ch == ' ') {
                if (word.size() > 1)
                    pushUnique(r.keywordTags, "keyword:" + word);
                word.clear();
            } else
                word.push_back(ch);
        }
        if (word.size() > 1)
            pushUnique(r.keywordTags, "keyword:" + word);
    }

    /// REQ-4.2.3.11: infer category/search tags from a natural-language Smart Search query.
    inline SearchReflection reflectSearchQuery(const std::string& query) {
        const std::string text = normalized(query);
        SearchReflection r;
        const std::string subject = subjectOf(text);
        if (subject != "general")
            addReflectedTag(r, "subject", subject);
        const std::string ext = extensionFromQuery(text);
        const std::string media = ext.empty() ? mediaTypeFromQuery(text) : mediaType(ext);
        if (media != "other")
            addReflectedTag(r, "media_type", media);
        if (!ext.empty())
            addReflectedTag(r, "extension",  ext.substr(1));
        const std::string docType = documentType(text, ext, "document");
        if (docType != "document")
            addReflectedTag(r, "document_type", docType);
        for (const char* sz : {"small", "medium", "large", "huge"})
            if (containsPhrase(text, sz))
                addReflectedTag(r, "size", sz);
        addKeywordReflection(r, query);
        for (const auto& tag : r.keywordTags)
            pushUnique(r.tags, tag);
        return r;
    }
}
